name: build and deploy for spring app
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Unit Tests
        run: mvn -B test --file pom.xml
        
      - name: Build with Maven
        run: |
          mvn clean package
          mvn -B package --file pom.xml
      

   